import React, {useCallback, useEffect, useState} from "react";
import axios from "axios";
import {Box, Button, Card, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Rating, Select, TextField, Typography} from "@mui/material";
import {API_BASE_URL} from "../../api";

const auth=()=>({token:localStorage.getItem("adminToken")});
export default function Reviews(){
 const [rows,setRows]=useState([]),[analytics,setAnalytics]=useState({distribution:{},trend:[],dealers:[]}),[filters,setFilters]=useState({rating:'',status:''}),[reply,setReply]=useState(null),[body,setBody]=useState('');
 const load=useCallback(async()=>{const params=Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==''));const [list,stats]=await Promise.all([axios.get(`${API_BASE_URL}/rating/admin`,{headers:auth(),params}),axios.get(`${API_BASE_URL}/rating/admin/analytics`,{headers:auth(),params})]);setRows(list.data.data||[]);setAnalytics(stats.data.data||{});},[filters]);
 useEffect(()=>{load().catch(console.error)},[load]);
 const moderate=async(id,action)=>{await axios.patch(`${API_BASE_URL}/rating/admin/${id}/moderate`,{action},{headers:auth()});load()};
 const sendReply=async()=>{await axios.post(`${API_BASE_URL}/rating/admin/${reply}/reply`,{body},{headers:auth()});setReply(null);setBody('');load()};
 const download=async()=>{const r=await axios.get(`${API_BASE_URL}/rating/admin/export.csv`,{headers:auth(),params:filters,responseType:'blob'}),u=URL.createObjectURL(r.data),a=document.createElement('a');a.href=u;a.download='reviews.csv';a.click();URL.revokeObjectURL(u)};
 return <Box sx={{p:{xs:2,md:3}}}><Box display="flex" justifyContent="space-between" alignItems="center" mb={3}><Box><Typography variant="h4" fontWeight={800}>Ratings & Reviews</Typography><Typography color="text.secondary">Moderate verified customer feedback and dealer responses.</Typography></Box><Button variant="outlined" onClick={download}>Export CSV</Button></Box>
 <Grid container spacing={2} mb={3}>{[["Average rating",`${analytics.averageRating||0} ★`],["Total reviews",analytics.reviewCount||0],["Pending replies",analytics.pendingReplies||0],["5-star reviews",analytics.distribution?.[5]||0]].map(([k,v])=><Grid item xs={6} md={3} key={k}><Card sx={{p:2.2}}><Typography color="text.secondary" fontSize={13}>{k}</Typography><Typography variant="h5" fontWeight={800} mt={.5}>{v}</Typography></Card></Grid>)}</Grid>
 <Card sx={{p:2,mb:2,display:'flex',gap:2,flexWrap:'wrap'}}><Select size="small" value={filters.rating} displayEmpty onChange={e=>setFilters(f=>({...f,rating:e.target.value}))}><MenuItem value="">All ratings</MenuItem>{[5,4,3,2,1].map(x=><MenuItem key={x} value={x}>{x} stars</MenuItem>)}</Select><Select size="small" value={filters.status} displayEmpty onChange={e=>setFilters(f=>({...f,status:e.target.value}))}><MenuItem value="">All moderation</MenuItem><MenuItem value="published">Published</MenuItem><MenuItem value="hidden">Hidden</MenuItem><MenuItem value="spam">Spam</MenuItem></Select></Card>
 <Box display="grid" gap={1.5}>{rows.map(r=><Card key={r._id} sx={{p:2}}><Box display="flex" justifyContent="space-between" gap={2} flexWrap="wrap"><Box flex={1} minWidth={260}><Box display="flex" gap={1} alignItems="center"><Rating value={r.rating} readOnly size="small"/><Chip size="small" label={r.moderationStatus} color={r.moderationStatus==='published'?'success':'default'}/>{r.isFeatured&&<Chip size="small" label="Featured" color="warning"/>}</Box><Typography fontWeight={750} mt={1}>{r.isAnonymous?'Anonymous customer':`${r.user_id?.first_name||''} ${r.user_id?.last_name||''}`}</Typography><Typography variant="body2" color="text.secondary">{r.dealer_id?.shopName||'Dealer'} · {new Date(r.createdAt).toLocaleDateString()}</Typography><Typography mt={1}>{r.comment||r.review||'No written comment'}</Typography>{r.images?.length>0&&<Box display="flex" gap={1} mt={1}>{r.images.map(i=><Box key={i._id} component="img" src={i.url} sx={{width:64,height:64,objectFit:'cover',borderRadius:1}}/>)}</Box>}{r.reply&&<Box bgcolor="#f8fafc" p={1.3} borderRadius={1} mt={1}><Typography fontSize={12} fontWeight={700}>{r.reply.authorType} reply</Typography><Typography fontSize={13}>{r.reply.body}</Typography></Box>}</Box><Box display="flex" gap={1} alignItems="flex-start" flexWrap="wrap"><Button size="small" onClick={()=>moderate(r._id,r.moderationStatus==='hidden'?'publish':'hide')}>{r.moderationStatus==='hidden'?'Publish':'Hide'}</Button><Button size="small" onClick={()=>moderate(r._id,r.isFeatured?'unfeature':'feature')}>{r.isFeatured?'Unfeature':'Feature'}</Button><Button size="small" color="error" onClick={()=>moderate(r._id,'spam')}>Spam</Button>{!r.reply&&<Button size="small" variant="contained" onClick={()=>setReply(r._id)}>Reply</Button>}</Box></Box></Card>)}</Box>
 <Dialog open={!!reply} onClose={()=>setReply(null)} fullWidth><DialogTitle>Reply as Admin</DialogTitle><DialogContent><TextField autoFocus multiline rows={4} fullWidth sx={{mt:1}} value={body} onChange={e=>setBody(e.target.value)} inputProps={{maxLength:1000}}/></DialogContent><DialogActions><Button onClick={()=>setReply(null)}>Cancel</Button><Button variant="contained" disabled={!body.trim()} onClick={sendReply}>Send reply</Button></DialogActions></Dialog></Box>
}
